### ISSUE TITLE
Aroma DB duplicate CIDs

### ISSUE THREAD

**Issue by joelmainland** [pyrfume/pyrfume-data#102]
AromaDB has several duplicates with different descriptions. Example CID 179 is described as buttery, buttery aroma, and fruity in different entries. I'm not sure if these should be merged into one entry.

**Comment by rgerkin** [comment]
This is an alternative format, and more in line with how a table in a relational database would look (i.e. "normalized" which means one value per entry, so a key has multiple values it must be across multiple entries).  But it is inconsistent with how some of the others are currently represented (with a sparse and dense version: sparse is semicolon separated list and dense is one column per descriptor, cells filled with 1 and 0).  Which version plays best with your app or other scripts?

**Comment by joelmainland** [comment]
I can work with both--I'll close this issue since I think I just need to familiarize myself with how AromaDB is put together. I don't know that it is worth creating a sparse/dense version ourselves, vs. leaving that to the user.
