### ISSUE TITLE
Cite Pyrfume

### ISSUE THREAD

**Issue by MatejHl** [pyrfume/pyrfume-data#175]
Hi,

first of all, this is a great project and thank you for putting all the datasets to one place!
Since we're working with this data, I'd like to cite Pyrfume in our paper.  I was wandering, is there some preferred way to cite Pyrfume in a paper? 

Thanks.

Best,
    Matej

**Comment by rgerkin** [comment]
You can cite the preprint: https://www.biorxiv.org/content/10.1101/2022.09.08.507170
