### ISSUE TITLE
burton_2022

### ISSUE THREAD

**Issue by XiaochenFu** [pyrfume/pyrfume-data#179]
The data from burton_2022 seems to be from burton_2019. The mice are same but the ROI positions are different in the two papers

burton_2022: https://elifesciences.org/articles/80470
burton_2019: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6410398/

**Comment by rgerkin** [comment]
@TravisGould Could you take a look?

**Comment by rgerkin** [comment]
Fixed by #181.
