### ISSUE TITLE
metrics for odors

### ISSUE THREAD

**Issue by zokie** [pyrfume/pyrfume-data#187]
It's great to see such a fantastic job. I'm a novice in the field of olfactory research, and I'm looking for some metrics, either physical or chemical, to quantify pleasant and unpleasant odors. Do you have any relevant literature to recommend?

**Comment by rgerkin** [comment]
You can use model predictions, such as from https://pubmed.ncbi.nlm.nih.gov/28219971/ or build your own from the data there or from https://bmcneurosci.biomedcentral.com/articles/10.1186/s12868-016-0287-2 or from https://www.jneurosci.org/content/27/37/10015.  One heuristic is that more "complex" molecules are often rated as more pleasant.
