### ISSUE TITLE
Keller2016, Only Dream Version

### ISSUE THREAD

**Issue by Farzaneh-Taleb** [pyrfume/pyrfume-data#221]
I ran main.py for keller_2016  and the original one runs without error. However if I change to the following:
 only_dream_subjects=True,
 only_dream_descriptors=True
 only_dream_molecules=True

I get the following error:
RemoteDataError: Could not get file at https://raw.githubusercontent.com/pyrfume/pyrfume-data/main/keller_2017/cids.csv

Is there any other way to get the data only for DREAM challenge?

**Comment by rgerkin** [comment]
@Farzaneh-Taleb It looks like [this line](https://github.com/pyrfume/pyrfume/blob/f9a1261edd207a6e726470bcc6285ac1fa1b1982/pyrfume/dream.py#L63) gets PubChem compounds ids in a deprecated way.  You should submit a pull request to replace that with a similar `pyrfume.load_data` of the `keller_2017/molecules.csv` file, and use the `CID` column there.  If it works for you, I'll merge the PR.
