### ISSUE TITLE
Ravia2020, behavior_ 2.csv seems incomplete.

### ISSUE THREAD

**Issue by Farzaneh-Taleb** [pyrfume/pyrfume-data#222]
The number of rows in behavior_2.csv doesn't match with what is expected based on the description of the experimentin the paper. The data is only for one subject of averaged or....?

**Comment by rgerkin** [comment]
It is for experiments 1 and 2 from the paper, as documented in the extraction code [here](https://github.com/pyrfume/pyrfume-data/blob/main/ravia_2020/main.py).  As you can see there, the source data is from their supplementary material, tableS2.csv, which appears to already be subject-averaged.
