### ISSUE TITLE
Goodscents Indexing

### ISSUE THREAD

**Issue by joelmainland** [pyrfume/pyrfume-data#95]
goodscents/behavior.csv is indexed by TGSC.ID instead of CID. TGSC.ID does not appear in goodscents/molecules.csv

**Comment by rgerkin** [comment]
TSGC.ID is linked to CID by identifiers.csv.  This allow the full GoodScents data to be included even in those cases where a CID could not be obtained for a given structure.  In other words, an inner join of identifiers and behavior will retain those GoodScents entries that have a CID, which can then be looked up in molecules.csv.

**Comment by rgerkin** [comment]
I know there is some harmonization that needs to be done next week.

**Comment by SimonEnsemble** [comment]
I did three joins to get a molecule, odor table.

6157 rows in `behavior_sparse.csv`. I join with `identifiers.csv` on the `"TGSC ID"`.
I then join _this_ table with `molecules.csv` on `"CID"`.

oddly, after the (inner) join, I am left with only 5702 rows... so some `"TGSC ID"` in `behaviors.csv` is not in `identifiers.csv`. 😢

**Comment by rgerkin** [comment]
Fixed in #176
