### ISSUE TITLE
Dravnieks molecules.csv

### ISSUE THREAD

**Issue by joelmainland** [pyrfume/pyrfume-data#99]
The molecules.csv file does not have an identifier in common with either behavior_1 or behavior_2.

**Comment by rgerkin** [comment]
Per the new arrangement, molecules.csv provides the compounds only.
identifiers.csv links the stimulus names to those compounds (and other
information like concentrations, etc.), and then behavior files are indexed
by stimulus names.

**Comment by joelmainland** [comment]
Someday I will remember this. Sorry!
